const jobs = [
    {
        id: "1",
        title: "Software Engineer",
        company: {
            id: "1",
            name: "SoftPro Tech",
            email: "careers@software.tech",
            website: "softpro.tech",
            description: "We are a tech company focused on delivering software solutions.",
            registration_date: "2024-06-30T12:00:00Z",
            job_opportunities_posted: 10,
            candidates_hired: 30
        },
        posted_on: "2024-07-01T12:00:00Z",
        work_type: "Work From Office",
        description: "Software development",
        job_type: "Full Time",
        start_date: "2024-07-05T12:00:00Z",
        salary_or_stipend: "3000000",
        apply_by: "2024-07-04T12:00:00Z",
        applicants_count: 2,
        skills_required: ['Python', 'ReactJS', 'Java'],
        openings: 3,
        perks: ['Flexible work hours']
    },
    {
        id: "2",
        title: "Frontend Developer",
        company: {
            id: "2",
            name: "TechWave Solutions",
            email: "careers@techwave.com",
            website: "techwave.com",
            description: "Innovative solutions for the modern web.",
            registration_date: "2024-05-30T12:00:00Z",
            job_opportunities_posted: 5,
            candidates_hired: 20
        },
        posted_on: "2024-06-28T12:00:00Z",
        work_type: "Remote",
        description: "Building responsive web applications.",
        job_type: "Part Time",
        start_date: "2024-07-15T12:00:00Z",
        salary_or_stipend: "2000000",
        apply_by: "2024-07-10T12:00:00Z",
        applicants_count: 150,
        skills_required: ['HTML', 'CSS', 'JavaScript', 'ReactJS'],
        openings: 2,
        perks: ['Remote work', 'Health insurance']
    },
    {
        id: "3",
        title: "Backend Developer",
        company: {
            id: "3",
            name: "Innovatech",
            email: "careers@innovatech.com",
            website: "innovatech.com",
            description: "Leading the way in tech innovations.",
            registration_date: "2023-08-20T12:00:00Z",
            job_opportunities_posted: 15,
            candidates_hired: 50
        },
        posted_on: "2024-06-25T12:00:00Z",
        work_type: "Hybrid",
        description: "Developing robust backend services.",
        job_type: "Full Time",
        start_date: "2024-07-20T12:00:00Z",
        salary_or_stipend: "3500000",
        apply_by: "2024-07-18T12:00:00Z",
        applicants_count: 180,
        skills_required: ['Node.js', 'Express', 'MongoDB'],
        openings: 5,
        perks: ['Hybrid work', 'Gym membership']
    },
    {
        id: "4",
        title: "Data Scientist",
        company: {
            id: "4",
            name: "DataXpert",
            email: "careers@dataxpert.com",
            website: "dataxpert.com",
            description: "Data-driven solutions for complex problems.",
            registration_date: "2024-01-15T12:00:00Z",
            job_opportunities_posted: 8,
            candidates_hired: 40
        },
        posted_on: "2024-07-05T12:00:00Z",
        work_type: "Remote",
        description: "Analyzing and interpreting complex data.",
        job_type: "Full Time",
        start_date: "2024-07-25T12:00:00Z",
        salary_or_stipend: "4000000",
        apply_by: "2024-07-22T12:00:00Z",
        applicants_count: 220,
        skills_required: ['Python', 'R', 'SQL'],
        openings: 4,
        perks: ['Remote work', 'Stock options']
    },
    {
        id: "5",
        title: "DevOps Engineer",
        company: {
            id: "5",
            name: "CloudNet",
            email: "careers@cloudnet.com",
            website: "cloudnet.com",
            description: "Cloud solutions for modern businesses.",
            registration_date: "2022-11-10T12:00:00Z",
            job_opportunities_posted: 12,
            candidates_hired: 35
        },
        posted_on: "2024-07-03T12:00:00Z",
        work_type: "Work From Office",
        description: "Managing cloud infrastructure.",
        job_type: "Full Time",
        start_date: "2024-07-15T12:00:00Z",
        salary_or_stipend: "3200000",
        apply_by: "2024-07-12T12:00:00Z",
        applicants_count: 170,
        skills_required: ['AWS', 'Docker', 'Kubernetes'],
        openings: 2,
        perks: ['Health insurance', 'Paid time off']
    },
    {
        id: "6",
        title: "Full Stack Developer",
        company: {
            id: "6",
            name: "TechWorld",
            email: "careers@techworld.com",
            website: "techworld.com",
            description: "End-to-end tech solutions.",
            registration_date: "2023-05-05T12:00:00Z",
            job_opportunities_posted: 20,
            candidates_hired: 60
        },
        posted_on: "2024-06-22T12:00:00Z",
        work_type: "Hybrid",
        description: "Developing full stack web applications.",
        job_type: "Full Time",
        start_date: "2024-07-10T12:00:00Z",
        salary_or_stipend: "3400000",
        apply_by: "2024-07-08T12:00:00Z",
        applicants_count: 200,
        skills_required: ['JavaScript', 'Node.js', 'ReactJS', 'MongoDB'],
        openings: 3,
        perks: ['Hybrid work', 'Flexible schedule']
    },
    {
        id: "7",
        title: "Machine Learning Engineer",
        company: {
            id: "7",
            name: "AI Innovations",
            email: "careers@aiinnovations.com",
            website: "aiinnovations.com",
            description: "Pioneering AI solutions.",
            registration_date: "2023-12-01T12:00:00Z",
            job_opportunities_posted: 10,
            candidates_hired: 45
        },
        posted_on: "2024-06-20T12:00:00Z",
        work_type: "Remote",
        description: "Developing machine learning models.",
        job_type: "Full Time",
        start_date: "2024-07-15T12:00:00Z",
        salary_or_stipend: "3800000",
        apply_by: "2024-07-10T12:00:00Z",
        applicants_count: 210,
        skills_required: ['Python', 'TensorFlow', 'PyTorch'],
        openings: 2,
        perks: ['Remote work', 'Stock options']
    },
    {
        id: "8",
        title: "UI/UX Designer",
        company: {
            id: "8",
            name: "Creative Minds",
            email: "careers@creativeminds.com",
            website: "creativeminds.com",
            description: "Innovative designs for digital products.",
            registration_date: "2023-03-10T12:00:00Z",
            job_opportunities_posted: 7,
            candidates_hired: 25
        },
        posted_on: "2024-07-04T12:00:00Z",
        work_type: "Work From Office",
        description: "Designing user-friendly interfaces.",
        job_type: "Full Time",
        start_date: "2024-07-20T12:00:00Z",
        salary_or_stipend: "3000000",
        apply_by: "2024-07-15T12:00:00Z",
        applicants_count: 130,
        skills_required: ['Sketch', 'Figma', 'Adobe XD'],
        openings: 1,
        perks: ['Health insurance', 'Gym membership']
    },
    {
        id: "9",
        title: "Cybersecurity Analyst",
        company: {
            id: "9",
            name: "SecureTech",
            email: "careers@securetech.com",
            website: "securetech.com",
            description: "Ensuring digital security.",
            registration_date: "2024-02-25T12:00:00Z",
            job_opportunities_posted: 6,
            candidates_hired: 20
        },
        posted_on: "2024-06-28T12:00:00Z",
        work_type: "Remote",
        description: "Monitoring and securing networks.",
        job_type: "Full Time",
        start_date: "2024-07-18T12:00:00Z",
        salary_or_stipend: "3100000",
        apply_by: "2024-07-14T12:00:00Z",
        applicants_count: 110,
        skills_required: ['Network Security', 'Penetration Testing', 'SIEM'],
        openings: 3,
        perks: ['Remote work', 'Health insurance']
    },
    {
        id: "10",
        title: "Product Manager",
        company: {
            id: "10",
            name: "ProdMaster",
            email: "careers@prodmaster.com",
            website: "prodmaster.com",
            description: "Leading product management.",
            registration_date: "2023-09-05T12:00:00Z",
            job_opportunities_posted: 5,
            candidates_hired: 15
        },
        posted_on: "2024-07-02T12:00:00Z",
        work_type: "Work From Office",
        description: "Managing product lifecycle.",
        job_type: "Full Time",
        start_date: "2024-07-25T12:00:00Z",
        salary_or_stipend: "4500000",
        apply_by: "2024-07-20T12:00:00Z",
        applicants_count: 140,
        skills_required: ['Product Management', 'Agile', 'Scrum'],
        openings: 1,
        perks: ['Health insurance', 'Flexible schedule']
    },
    {
        id: "11",
        title: "QA Engineer",
        company: {
            id: "11",
            name: "QualityWorks",
            email: "careers@qualityworks.com",
            website: "qualityworks.com",
            description: "Ensuring quality in every product.",
            registration_date: "2023-11-15T12:00:00Z",
            job_opportunities_posted: 8,
            candidates_hired: 30
        },
        posted_on: "2024-06-29T12:00:00Z",
        work_type: "Hybrid",
        description: "Testing software applications.",
        job_type: "Full Time",
        start_date: "2024-07-18T12:00:00Z",
        salary_or_stipend: "2700000",
        apply_by: "2024-07-14T12:00:00Z",
        applicants_count: 160,
        skills_required: ['Selenium', 'Jenkins', 'Test Automation'],
        openings: 4,
        perks: ['Hybrid work', 'Paid time off']
    },
    {
        id: "12",
        title: "Business Analyst",
        company: {
            id: "12",
            name: "BizAnalytica",
            email: "careers@bizanalytica.com",
            website: "bizanalytica.com",
            description: "Analyzing business processes for improvement.",
            registration_date: "2023-10-20T12:00:00Z",
            job_opportunities_posted: 6,
            candidates_hired: 25
        },
        posted_on: "2024-07-05T12:00:00Z",
        work_type: "Remote",
        description: "Analyzing and improving business processes.",
        job_type: "Full Time",
        start_date: "2024-07-25T12:00:00Z",
        salary_or_stipend: "3500000",
        apply_by: "2024-07-20T12:00:00Z",
        applicants_count: 140,
        skills_required: ['Business Analysis', 'SQL', 'Data Analysis'],
        openings: 2,
        perks: ['Remote work', 'Health insurance']
    }
];

export default jobs;
